---
- name: Configure development environment
  hosts: localhost
  become: false

  pre_tasks:
    - name: Detect OS
      set_fact:
        is_macos: "{{ ansible_facts['os_family'] == 'Darwin' }}"
        is_arch: "{{ ansible_facts['distribution'] == 'Archlinux' }}"
        is_ubuntu: "{{ ansible_facts['distribution'] == 'Ubuntu' }}"
      tags: ['always']

  roles:
    - role: macos
      when: is_macos
      tags: macos
    - role: linux
      when: is_arch or is_ubuntu
      tags: ['arch', 'ubuntu']
    - role: common  # Shared configurations (neovim, tmux)
