---
- name: Install common libraries
  community.general.homebrew:
    name: "{{ item }}"
    update_homebrew: true
    state: present
    install_options: ["formula"]
  loop:
  - cmake
  - gettext
  - git
  - node
  - btop
  - ninja
  - lua
  - jupyterlab
  - ripgrep
  - uv

- name: Include zsh setup tasks
  include_tasks: zsh.yml
  tags: ['zsh', 'zsh_config']

- name: Include fzf setup tasks
  include_tasks: fzf.yml
  tags: 'fzf'

- name: Include zoxide setup tasks
  include_tasks: zoxide.yml
  tags: 'zoxide'

- name: Include eza setup tasks
  include_tasks: eza.yml
  tags: 'eza'

- name: Include neovim setup tasks
  include_tasks: neovim.yml
  tags: ['neovim', 'neovim_config']

- name: Include tmux setup tasks
  include_tasks: tmux.yml
  tags: ['tmux', 'tmux_config']

- name: Include black setup tasks
  include_tasks: black.yml
  tags: 'black'

- name: Include ghostty setup tasks
  include_tasks: ghostty.yml
  tags: ['ghostty_config']
