---
- name: Set miniconda directory
  tags: conda
  set_fact:
    miniconda_dir: "{{ ansible_env.HOME }}/personal/miniconda3"

- name: Set miniconda script path
  set_fact:
    miniconda_script: "{{ miniconda_dir }}/miniconda.sh"
  tags: conda

- name: Set miniconda URL
  when: is_ubuntu
  set_fact:
    miniconda_url: 
  tags: conda

- name: Ensure Miniconda directory exists
  tags: conda
  file:
    path: "{{ ansible_env.HOME }}/personal/miniconda3"
    state: directory
    mode: "0755"

- name: Download Miniconda install script
  tags: conda
  when: is_macos
  get_url:
    url: "https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-arm64.sh" 
    dest: "{{ ansible_env.HOME }}/personal/miniconda3/miniconda.sh"
    mode: "0755"

- name: Download Miniconda install script
  tags: conda
  when: is_ubuntu
  get_url:
    url: "https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh" 
    dest: "{{ ansible_env.HOME }}/personal/miniconda3/miniconda.sh"
    mode: "0755"

- name: Run Miniconda installer
  tags: conda
  command:
    cmd: "bash {{ ansible_env.HOME }}/personal/miniconda3/miniconda.sh -b -u -p {{ ansible_env.HOME }}/personal/miniconda3"
  args:
    creates: "{{ ansible_env.HOME }}/personal/miniconda3/bin/conda"

- name: Remove Miniconda installer script
  tags: conda
  file:
    path: "{{ ansible_env.HOME }}/personal/miniconda3/miniconda.sh"
    state: absent

- name: Init conda
  tags: conda
  shell: |
    source {{ ansible_env.HOME }}/personal/miniconda3/bin/activate
    conda init --all
    conda config --set auto_activate_base false

- name: Add conda alias
  tags: conda
  blockinfile:
    path: "{{ lookup('env', 'HOME') }}/.zshrc"
    block: |
      alias "ac"="conda activate"
      alias "dc"="conda deactivate"
    create: yes
    validate: "zsh -n %s"
