---
- name: install neovim
  tags: neovim
  community.general.homebrew:
    name: "neovim"
    update_homebrew: true
    state: present
    install_options: ["formula"]

- name: Add nvim alias
  tags: neovim_config
  lineinfile:
    path: "{{ lookup('env', 'HOME') }}/.zshrc"
    line: 'alias "vi"="nvim"'
    state: present
    create: yes
    validate: "zsh -n %s"


- name: ensure neovim config directory exists
  tags: ['neovim_config', 'neovim']
  file:
    path: "{{ lookup('env', 'HOME') }}/.config/nvim"
    state: directory
    mode: '0755'

- name: sync neovim configuration files
  tags: ['neovim_config', 'neovim']
  copy:
    src: nvim/
    dest: "{{ lookup('env', 'HOME') }}/.config/nvim/"
    mode: '0644'
