---
- name: clone or update tmux
  tags: tmux
  git:
    repo: https://github.com/tmux/tmux.git
    dest: "{{ lookup('env', 'HOME') }}/personal/tmux"
    single_branch: yes
    version: 3.5
    update: yes
    force: no

- name: run autogen.sh
  tags: tmux
  shell: "sh autogen.sh && ./configure"
  args:
    chdir: "{{ lookup('env', 'HOME') }}/personal/tmux" 

- name: make tmux
  tags: tmux
  make:
    chdir: "{{ lookup('env', 'HOME') }}/personal/tmux" 

- name: install tmux plugin manager (tpm)
  tags: tmux
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ lookup('env', 'HOME') }}/.tmux/plugins/tpm"

- name: ensure tmux config directory exists
  tags: ['tmux_config', 'tmux']
  file:
    path: "{{ lookup('env', 'HOME') }}/.config/tmux"
    state: directory
    mode: '0755'

- name: sync tmux configuration files
  tags: ['tmux_config', 'tmux']
  copy:
    src: tmux/
    dest: "{{ lookup('env', 'HOME') }}/.config/tmux/"
    mode: '0644'

- name: ensure scripts directory exists
  tags: ['tmux_config', 'tmux']
  file:
    path: "{{ lookup('env', 'HOME') }}/.local/scripts"
    state: directory
    mode: '0755'

- name: sync tmux-sessionizer
  tags: ['tmux_config', 'tmux']
  copy:
    src: nav/
    dest: "{{ lookup('env', 'HOME') }}/.local/scripts"
    mode: preserve
