---
- name: Install yapf
  community.general.homebrew:
    name: yapf
    state: present

- name: Add yapf alias
  lineinfile:
    path: "{{ lookup('env', 'HOME') }}/.zshrc"
    line: 'alias "yy"="yapf --in-place --recursive ."'
    state: present
    create: yes
    validate: "zsh -n %s"
    marker: "# {mark} ANSIBLE MANAGED BLOCK yapf"

- name: Ensure yapf config directory does not exist (remove if present)
  tags: 'yapf'
  file:
    path: "{{ lookup('env', 'HOME') }}/.config/yapf"
    state: absent

- name: ensure yapf config directory exists
  tags: 'yapf'
  file:
    path: "{{ lookup('env', 'HOME') }}/.config/yapf"
    state: directory
    mode: '0755'

- name: sync yapf configuration files
  tags: 'yapf'
  copy:
    src: yapf/
    dest: "{{ lookup('env', 'HOME') }}/.config/yapf/"
    mode: '0644'

